{% set name = "pwtools" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/elcorto/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 0805c8d220a0b23e84ec94816e9b34428096ab3c7a48851dd27ca806c92a976d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [win or py>=312 or py<=39]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
  host:
    - python
    - pip
    - meson-python
    - numpy
    - libblas
    - libcblas
    - liblapack
    - liblapacke
  run:
    - python
    - matplotlib-base
    - nose
    - numpy
    - scipy
    - h5py
    - ase
    - numpydoc
    - pycifrw
    - spglib

test:
  imports:
    - pwtools

about:
  home: http://elcorto.github.io/pwtools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: pwtools is a Python package for pre- and postprocessing of atomistic calculations, mostly targeted to Quantum Espresso, CPMD, CP2K and LAMMPS.

  description: |
    pwtools is a Python package for pre- and postprocessing of atomistic 
    calculations, mostly targeted to Quantum Espresso, CPMD, CP2K and 
    LAMMPS. It is almost, but not quite, entirely unlike ASE, with some 
    tools extending numpy/scipy. It has a set of powerful parsers and 
    data types for storing calculation data.
  doc_url: http://elcorto.github.io/pwtools
  dev_url: https://github.com/elcorto/pwtools

extra:
  recipe-maintainers:
    - jan-janssen
